<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <ApplicationIcon>Resources\CBRE.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\CBRE.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CBRE.Packages\CBRE.Packages.csproj" />
  </ItemGroup>
</Project>
