<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <RootNamespace>CBRE.DataStructures</RootNamespace>
    <AssemblyName>CBRE.DataStructures</AssemblyName>
    
    <TargetFramework>net48</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="OpenTK">
      <HintPath>..\OpenTK.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CBRE.Common\CBRE.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
