<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <RootNamespace>CBRE.Providers</RootNamespace>
    <AssemblyName>CBRE.Providers</AssemblyName>
    
    <TargetFramework>net48</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CBRE.Common\CBRE.Common.csproj" />
    <ProjectReference Include="..\CBRE.DataStructures\CBRE.DataStructures.csproj" />
    <ProjectReference Include="..\CBRE.FileSystem\CBRE.FileSystem.csproj" />
    <ProjectReference Include="..\CBRE.Graphics\CBRE.Graphics.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Map\RMF22.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
  </ItemGroup>
</Project>
